### ISSUE TITLE
Cross compile for Amlogic aarch64 A53 

### ISSUE THREAD

**Issue by siliconhippy** [rickyzhang82/FreeBSDWiki#1]
Hi Ricky !

Looks like this is the only FOSS reference I found for pfSense for ARM, besides the proprietary netgate.

1. Does this work on RPi3/4?

2. Do you think this procedure will work for Amlogic ARM v8, A53 quad-core (e.g.,  S905W on a TV box)?

3. How about compiling for OpenSense?

Cheers,
🤠
Shippy.

**Comment by rickyzhang82** [comment]
1. I haven't tested it. But it should.
1. Yes. It either uses qemu or runs cross compiler. It should work for ARM.
1. I haven't tried the binary for OpenSense. But I got the port compiled in my i9900k box for my ARM based pfSense. It works.

Good luck.
